- package: gpkg.vtsnn
  version: 0.1
  data-files:
    - network_config/*

- model: data  
  description: >
      Model for processing raw data.
- operations:
    preprocess-cw:
      description: Preprocess raw data for Container & Weight Classification.
      main: vtsnn.preprocess
      requires:
        - config
      flags:
        save_path:
          required: true
        data_path:
          required: true
        tact_threshold: 0
        vis_threshold: 1
        selection: grasp_lift_hold
        bin_duration: 0.02
        n_sample_per_object: 40
        network_config: network_config/container_weight.yml
        task: cw
    preprocess-slip:
      description: Preprocess raw data for Slip Detection.
      main: vtsnn.preprocess
      requires:
        - config
      flags:
        save_path: /home/jethro/data_VTSNN_test/slip_data
        data_path: /datasets/eventdata/slip2/
        tact_threshold: 0
        vis_threshold: 0
        selection: full
        bin_duration: 0.001
        n_sample_per_object: 50
        network_config: network_config/slip_detection.yml
        task: slip
    
  resources:
    config:
      description: SNN network config yml files
      sources:
        - file: network_config

- model: analyse
  operations:
    vtsnn:
      description: Analyse SNNs
      main: vtsnn.analyse_snn
      requires:
        - config
      flags:
        runs:
          required: true
  resources:
    config:
      description: SNN network config yml files
      sources:
        - file: network_config

- model: vtsnn
  operations:
    train-cw:
      description: Train the VT-SNN model on Container & Weight Classification
      main: vtsnn.train_snn
      requires:
        - config
      flags:
        epochs: 500
        lr: 0.001
        sample_file: 1
        batch_size: 8
        data_dir:
          required: true
        network_config: network_config/container_weight.yml
        hidden_size: 32
        loss: NumSpikes
        mode:
          required: true
        task: cw
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test
    train-sd:
      description: Train the VT-SNN model on Slip Detection
      main: vtsnn.train_snn
      requires:
        - config
      flags:
        epochs: 500
        lr: 0.001
        sample_file: 1
        batch_size: 8
        data_dir:
          required: true
        network_config: network_config/slip_detection.yml
        hidden_size: 32
        loss: NumSpikes
        mode:
          required: true
        task: slip
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train        
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test
  resources:
    config:
      description: SNN network config yml files
      sources:
        - file: network_config

- model: mlp-gru
  operations:
    train-cw:
      description: Train the MLP-GRU on Container & Weight Classification
      main: vtsnn.train_mlp
      flags:
        epochs: 500
        lr: 0.0001
        sample_file: 1
        batch_size: 8
        data_dir:
          required: true
        hidden_size: 32
        mode:
          required: true
        task: cw
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train        
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test
    train-sd:
      description: Train the MLP-GRU model on Slip Detection
      main: vtsnn.train_mlp
      flags:
        epochs: 500
        lr: 0.0001
        sample_file: 1
        batch_size: 8
        data_dir:
          required: true
        hidden_size: 32
        mode:
          required: true
        task: slip
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train        
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test

- model: cnn3d
  operations:
    train-cw:
      description: Train the CNN3D model on Container & Weight Classification
      main: vtsnn.train_cnn3d
      flags:
        epochs: 1000
        lr: 0.00001
        sample_file: 1
        batch_size: 8
        data_dir:
          required: true
        mode:
          required: true
        task: cw
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train        
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test
    train-sd:
      description: Train the CNN3D model on Slip Detection
      main: vtsnn.train_cnn3d
      flags:
        epochs: 1000
        lr: 0.00001
        sample_file: 1
        batch_size: 8
        data_dir:
          required: true
        mode:
          required: true
        task: slip
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train        
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test

- config: loihi
  operations:
    train-sd:
      description: Train the Loihi model on Slip Detection
      main: vtsnn.train_loihi
      requires:
        - config
      flags:
        epochs: 500
        lr: 0.001
        sample_file: 1
        batch_size: 8
        data_dir:
          required: true
        network_config: network_config/slip_loihi.yml
        hidden_size: 32
        loss: NumSpikes
        mode:
          required: true
        task: slip
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train
        - loss/test as loss_test
        - acc/train as acc_train
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test
    benchmark-sd:
      description: Benchmark the Loihi model on Slip Detection
      main: vtsnn.benchmark
      requires:
        - config
      flags:
        sample_file: 1
        hidden_size: 32
        num_inf: 1000
        model_dir:
          required: true
        data_dir:
          required: true
        network_config: network_config/slip_loihi.yml
        log: gpu.yml
        mode:
          required: true
        task: slip
        delay: 0

  resources:
    config:
      description: SNN network config yml files
      sources:
        - file: network_config
