- model: vtsnn
  description: VT-SNN models
  sourcecode:
    select:
      - exclude: slayerPytorch
  operations:
    prepare-data:
      description: Preprocess data for training
      main: preprocess
      flags:
        save_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/
        tactile_path: /datasets/eventdata/batch2/aces_recordings/
        video_path: /datasets/eventdata/batch2/prophesee_recordings/
        trajectory_path: /datasets/eventdata/batch2/traj_start_ends/
        threshold: 1
        selection: grasp_lift_hold
        modes: vitac # vi, tac, vitac
        bin_duration: 0.02
        n_sample_per_object: 20
        remove_outlier: 0
    downsample-vision:
      description: Downsample vision data with sum pool and save as one file
      main: downsample_images
      flags:
        path: /home/tasbolat/some_python_examples/data_VT_SNN_new/
        theta: 10
        tsample: 325
        tauRho: 1
        count: 400 # total number of samples
    tact:
      description: Train tactile model using SNN
      main: train_tac_snn
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - epochs
        - tsample
        - tsr_stop
        - sc_true
        - sc_false
        - lr
        - theta
        - tauRho
        - sample_file
        - hidden_size
        - output_size
        - checkpoint_dir
      flags:
        batch_size: 8
        epochs: 500
        lr: 0.001
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/
        tsample: 325
        tauRho: 1
        tsr_stop: 325
        sc_true: 150
        sc_false: 5
        theta: 10
        sample_file: 1
        hidden_size: 32
        checkpoint_dir: . #/home/tasbolat/some_python_examples/VT_SNN/logged_models/
      compare:
        - =batch_size
        - =epochs
        - =tsample
        - =tsr_stop
        - =sc_true
        - =sc_false
        - =lr
        - =theta
        - =tauRho
        - =sample_file
        - =hidden_size
        - loss/train as loss_train
        - max acc/train as max_acc_train
        - loss/test as loss_test
        - max acc/test as max_acc_test
        - acc/test as acc_test
        - acc/train as acc_train