- package: gpkg.vtsnn
  version: 0.1
  data-files:
    - network_config/*

- model: data  
  description: >
      Model for processing raw data.
- operations:
    preprocess-cw:
      description: Preprocess raw data for Container & Weight Classification.
      main: vtsnn.preprocess
      requires:
        - config
      flags:
        save_path: /home/jethro/data_VTSNN_test/
        data_path: /datasets/eventdata/batch2/
        threshold: 1
        selection: grasp_lift_hold
        bin_duration: 0.02
        n_sample_per_object: 20
        network_config: network_config/container_weight.yml
        task: cw
    preprocess-slip:
      description: Preprocess raw data for Slip Detection.
      main: vtsnn.preprocess
      requires:
        - config
      flags:
        save_path: /home/jethro/data_VTSNN_test/slip_data
        data_path: /datasets/eventdata/slip2/
        threshold: 1
        selection: full
        bin_duration: 0.001
        n_sample_per_object: 50
        network_config: network_config/slip_detection.yml
        task: slip
    
  resources:
    config:
      description: SNN network config yml files
      sources:
        - file: network_config

- config: vtsnn-base
  operations:
    train-cw:
      description: Train the {{desc}} on Container & Weight Classification
      main: vtsnn.train_snn
      requires:
        - config
      flags:
        epochs: 500
        lr: 0.001
        sample_file: 1
        batch_size: 8
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/
        network_config: network_config/container_weight.yml
        hidden_size: 32
        loss: NumSpikes
        mode: '{{mode}}'
        task: cw
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test
    train-sd:
      description: Train the {{desc}} on Slip Detection
      main: vtsnn.train_snn
      requires:
        - config
      flags:
        epochs: 500
        lr: 0.001
        sample_file: 1
        batch_size: 8
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data
        network_config: network_config/slip_detection.yml
        hidden_size: 32
        loss: NumSpikes
        mode: '{{mode}}'
        task: slip
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train        
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test
  resources:
    config:
      description: SNN network config yml files
      sources:
        - file: network_config

- config: mlp-gru-base
  operations:
    train-cw:
      description: Train the {{desc}} on Container & Weight Classification
      main: vtsnn.train_mlp
      flags:
        epochs: 500
        lr: 0.0001
        sample_file: 1
        batch_size: 8
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/
        hidden_size: 32
        mode: '{{mode}}'
        task: cw
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train        
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test
    train-sd:
      description: Train the {{desc}} on Slip Detection
      main: vtsnn.train_mlp
      flags:
        epochs: 500
        lr: 0.0001
        sample_file: 1
        batch_size: 8
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data
        hidden_size: 32
        mode: '{{mode}}'
        task: slip
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train        
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test

- config: cnn3d-base
  operations:
    train-cw:
      description: Train the {{desc}} on Container & Weight Classification
      main: vtsnn.train_cnn3d
      flags:
        epochs: 1000
        lr: 0.00001
        sample_file: 1
        batch_size: 8
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/
        mode: '{{mode}}'
        task: cw
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train        
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test
    train-sd:
      description: Train the {{desc}} on Slip Detection
      main: vtsnn.train_cnn3d
      flags:
        epochs: 1000
        lr: 0.00001
        sample_file: 1
        batch_size: 8
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data
        mode: '{{mode}}'
        task: slip
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train        
        - loss/test as loss_test
        - acc/train as acc_train        
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test

- config: loihi-base
  operations:
    train-sd:
      description: Train the {{desc}} on Slip Detection
      main: vtsnn.train_loihi
      requires:
        - config
      flags:
        epochs: 500
        lr: 0.001
        sample_file: 1
        batch_size: 8
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data
        network_config: network_config/slip_loihi.yml
        hidden_size: 32
        loss: NumSpikes
        mode: '{{mode}}'
        task: slip
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =loss
        - loss/train as loss_train
        - loss/test as loss_test
        - acc/train as acc_train
        - acc/test as acc_test
        - max acc/train as max_acc_train
        - max acc/test as max_acc_test
  resources:
    config:
      description: SNN network config yml files
      sources:
        - file: network_config

- model: vtsnn-tact
  extends: vtsnn-base
  params:
    desc: VT-SNN tactile-only model
    mode: tact

- model: vtsnn-vis
  extends: vtsnn-base
  params:
    desc: VT-SNN vision-only model
    mode: vis

- model: vtsnn-mm
  extends: vtsnn-base
  params:
    desc: VT-SNN multi-modal model 
    mode: mm

- model: mlp-gru-tact
  extends: mlp-gru-base
  params:
    desc: MLP-GRU tactile-only model
    mode: tact

- model: mlp-gru-vis
  extends: mlp-gru-base
  params:
    desc: MLP-GRU vision-only model
    mode: vis

- model: mlp-gru-mm
  extends: mlp-gru-base
  params:
    desc: MLP-GRU multi-modal model
    mode: mm

- model: cnn3d-tact
  extends: cnn3d-base
  params:
    desc: CNN3D tactile-only model
    mode: tact

- model: cnn3d-vis
  extends: cnn3d-base
  params:
    desc: CNN3D vision-only model
    mode: vis

- model: cnn3d-mm
  extends: cnn3d-base
  params:
    desc: CNN3D multi-modal model
    mode: mm

- model: loihi-tact
  extends: loihi-base
  params:
    desc: Loihi tactile-only model
    mode: tact

- model: loihi-vis
  extends: loihi-base
  params:
    desc: Loihi vision-only model
    mode: vis

- model: loihi-mm
  extends: loihi-base
  params:
    desc: Loihi multi-modal model
    mode: mm
