- model: vtsnn
  description: VT-SNN models
  sourcecode:
    select:
      - exclude: slayerPytorch
  operations:
    prepare-data:
      description: Preprocess data for training
      main: preprocess --save_dir ../data_VT_SNN
      flags:
        tactile_path: /datasets/eventdata/batch2/aces_recordings/
        video_path: /datasets/eventdata/batch2/prophesee_recordings/
        trajectory_path: /datasets/eventdata/batch2/traj_start_ends/
        blacklist_path: /datasets/eventdata/batch2/blacklist.txt
        threshold: 1
        selection: grasp_lift_hold
        modes: tac
        bin_duration: 0.02
        remove_outlier: False
    tact:
      description: Train tactile model
      main: train_tac_snn
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - epochs
        - tsample
        - tsr_stop
        - sc_true
        - sc_false
        - lr
        - sample_file
        - hidden_size
        - output_size
        - checkpoint_dir
      flags:
        batch_size: 8
        epochs: 500
        lr: 0.01
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN/
        tsample: 325
        tsr_stop: 325
        sc_true: 150
        sc_false: 5
        sample_file: 1
        hidden_size: 32
        checkpoint_dir: /home/tasbolat/some_python_examples/VT_SNN/logged_models/
      compare:
        - =batch_size
        - =prob
        - =epochs
        - =tsample
        - =tsr_stop
        - =sc_true
        - =sc_false
        - =lr
        - =sample_file
        - =hidden_size
        - spike_loss/train as spike_loss_train
        - l1_loss/train as l1_loss_train
        - l2_loss/train as l2_loss_train
        - loss/train as loss_train
        - max acc/train as max_acc_train
        - l1_loss/test as l1_loss_test
        - l2_loss/test as l2_loss_test
        - loss/test as loss_test
        - max acc/test as max_acc_test
