- model: vtsnn
  description: VT-SNN models
  sourcecode:
    select:
      - exclude: slayerPytorch
  operations:
    tac_rpg:
      description: Train RPG model for tactile
      main: train_tac_rpg
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - epochs
        - lr
        - sample_file
        - checkpoint_dir
      flags:
        batch_size: 4
        epochs: 100
        lr: 0.0001
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_2/
        sample_file: 1
        checkpoint_dir: . #/home/tasbolat/some_python_examples/VT_SNN/logged_models/
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - loss/train as loss_train
        - max acc/train as max_acc_train
        - loss/test as loss_test
        - max acc/test as max_acc_test
        - acc/test as acc_test
        - acc/train as acc_train
    vis_rpg:
      description: Train RPG model for vision
      main: train_vis_rpg
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - epochs
        - lr
        - sample_file
        - checkpoint_dir
      flags:
        batch_size: 4
        epochs: 20
        lr: 0.0001
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN/
        sample_file: 1
        checkpoint_dir: . #/home/tasbolat/some_python_examples/VT_SNN/logged_models/
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - loss/train as loss_train
        - max acc/train as max_acc_train
        - loss/test as loss_test
        - max acc/test as max_acc_test
        - acc/test as acc_test
        - acc/train as acc_train