- package: vtsnn-slip
  version: 0.0.0
  data-files:
    - network_config/*.yml

- model: vtsnn-slip
  description: VT-SNN models for slip detection
  sourcecode:
    select:
      - exclude: slayerPytorch
  operations:
    prepare-data:
      description: Preprocess slip data for training for both modality
      main: preprocess_slip_data
      flags:
        save_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data/
        data_path: /datasets/eventdata/slip2/
        threshold: 1
        bin_duration: 0.001
    downsample:
      description: Downsample vision data with sum pool and save as one file for slip
      main: /home/tasbolat/some_python_examples/VT_SNN/downsample_images
      flags:
        path: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data
        theta: 10
        tsample: 150
        tauRho: 1
        count: 100 # total number of samples
    tact-snn:
      description: Train tactile model using SNN for slip
      main: /home/tasbolat/some_python_examples/VT_SNN/train_tac_snn
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - epochs
        - tsample
        - tsr_stop
        - sc_true
        - sc_false
        - lr
        - theta
        - tauRho
        - sample_file
        - hidden_size
        - output_size
        - checkpoint_dir
        - loss_type
      flags:
        batch_size: 8
        epochs: 700
        lr: 0.001
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data/
        tsample: 150
        tauRho: 1
        tsr_stop: 150
        sc_true: 80
        sc_false: 5
        theta: 10
        sample_file: 1
        hidden_size: 32
        checkpoint_dir: . 
        loss_type: 0
        output_size: 2
      compare:
        - =batch_size
        - =epochs
        - =vtsnn-slip:tact-snn tsample
        - =vtsnn-slip:tact-snn tsr_stop
        - =sc_true
        - =sc_false
        - =lr
        - =theta
        - =tauRho
        - =sample_file
        - =hidden_size
        - =loss_type
        - =output_size
        - loss/train as loss_train
        - max acc/train as max_acc_train
        - loss/test as loss_test
        - max acc/test as max_acc_test
        - acc/test as acc_test
        - acc/train as acc_train
    vis-snn:
      description: Train vizual model for slip
      main: /home/tasbolat/some_python_examples/VT_SNN/train_vis_snn
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - epochs
        - tsample
        - tsr_start
        - tsr_stop
        - sc_true
        - sc_false
        - hidden_size
        - lr
        - sample_file
        - output_size
        - checkpoint_dir
        - theta
        - tauRho
        - loss_type
      flags:
        batch_size: 8
        epochs: 500
        lr: 0.001
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data/
        tsample: 150
        tsr_start: 0
        tsr_stop: 150
        sc_true: 80
        sc_false: 5
        sample_file: 1
        output_size: 2
        theta: 10
        tauRho: 1
        hidden_size: 32
        checkpoint_dir: .
        loss_type: 0
      compare:
        - =batch_size
        - =epochs
        - =tsample
        - =tsr_stop
        - =sc_true
        - =sc_false
        - =lr
        - =sample_file
        - =hidden_size
        - =theta
        - =tauRho
        - =loss_type
        - loss/train as loss_train
        - max acc/train as max_acc_train
        - acc/train as acc_train
        - loss/test as loss_test
        - acc/test as acc_test
        - max acc/test as max_acc_test
    mm-snn:
      description: Train MM model for slip
      main: /home/tasbolat/some_python_examples/VT_SNN/train_mm_snn
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - epochs
        - tsample
        - tsr_start
        - tsr_stop
        - sc_true
        - sc_false
        - lr
        - sample_file
        - theta
        - tauRho
        - output_size
        - loss_type
      flags:
        batch_size:
          default: 8
        epochs:
          default: 500
        lr:
          default: 0.001
        data_dir:
          default: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data/
        tsample:
          default: 150
        tsr_start:
          default: 0
        tsr_stop:
          default: 150
        sc_true:
          default: 80
        sc_false:
          default: 5
        sample_file:
          default: 1        
        output_size:
          default: 2
        checkpoint_dir: .
        theta: 10
        tauRho: 1
        loss_type: 0
      compare:
        - =batch_size
        - =prob
        - =epochs
        - =tsample
        - =tsr_stop
        - =sc_true
        - =sc_false
        - =lr
        - =sample_file
        - =theta
        - =tauRho
        - =loss_type
        - loss/train as loss_train
        - max acc/train as max_acc_train
        - loss/test as loss_test
        - acc/test as acc_test
        - acc/train as acc_train
        - max acc/test as max_acc_test
    tact-ann:
      description: Train tactile model using ANN (MLP-GRU)
      main: /home/tasbolat/some_python_examples/VT_SNN/train_tac_ann
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - epochs
        - lr
        - sample_file
        - hidden_size
        - output_size
        - checkpoint_dir
      flags:
        batch_size: 8
        epochs: 600
        lr: 0.0001
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data/
        sample_file: 1
        hidden_size: 32
        output_size: 2
        checkpoint_dir: .
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =output_size
        - loss/train as loss_train
        - max acc/train as max_acc_train
        - loss/test as loss_test
        - max acc/test as max_acc_test
        - acc/test as acc_test
        - acc/train as acc_train
    vis-ann:
      description: Train vision model using ANN (MLP-GRU)
      main: /home/tasbolat/some_python_examples/VT_SNN/train_vis_ann
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - epochs
        - lr
        - sample_file
        - hidden_size
        - output_size
        - checkpoint_dir
        - output_size
      flags:
        batch_size: 8
        epochs: 400
        lr: 0.0001
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data/
        sample_file: 1
        hidden_size: 32
        checkpoint_dir: .
        output_size: 2
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =output_size
        - loss/train as loss_train
        - max acc/train as max_acc_train
        - loss/test as loss_test
        - max acc/test as max_acc_test
        - acc/test as acc_test
        - acc/train as acc_train
    mm-ann:
      description: Train multimodal model using ANN (MLP-GRU)
      main: /home/tasbolat/some_python_examples/VT_SNN/train_mm_ann
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - epochs
        - lr
        - sample_file
        - hidden_size
        - output_size
        - checkpoint_dir
      flags:
        batch_size: 8
        epochs: 400
        lr: 0.0001
        data_dir: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data/
        sample_file: 1
        hidden_size: 32
        output_size: 2
        checkpoint_dir: . 
      compare:
        - =batch_size
        - =epochs
        - =lr
        - =sample_file
        - =hidden_size
        - =output_size
        - loss/train as loss_train
        - max acc/train as max_acc_train
        - loss/test as loss_test
        - max acc/test as max_acc_test
        - acc/test as acc_test
        - acc/train as acc_train
    make-tactile-rectangular:
      description: Converts tactile data into rectangular shape for slip
      main: /home/tasbolat/some_python_examples/VT_SNN/cnn_files/tactile_rectangular_shape
      flags:
        path: /home/tasbolat/some_python_examples/data_VT_SNN_new/slip_data/