- model: vt_optimize
  description: VT-SNN models
  sourcecode:
    select:
      - exclude: slayerPytorch
  operations:
    tact:
      description: Train tactile model
      main: tact_analysis
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - lr
        - sample_file
        - cuda
      flags:
        batch_size: 8
        lr: 0.01
        sample_file: 2
        cuda: 1
      compare:
        - =batch_size
        - =lr
        - =sample_file
    vis:
      description: Train tactile model
      main: vis_analysis
      output-scalars: no
      objective:
        maximize: acc/test
      flags-import:
        - batch_size
        - lr
        - sample_file
        - cuda
      flags:
        batch_size: 8
        lr: 0.01
        sample_file: 2
        cuda: 1
      compare:
        - =batch_size
        - =lr
        - =sample_file